// <auto-generated />
using System;
using LuminousStudio.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuminousStudio.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260315200747_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuminousStudio.Infrastructure.Data.Entities.LampStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LampStyleName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("LampStyles");
                });

            modelBuilder.Entity("LuminousStudio.Infrastructure.Data.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("LuminousStudio.Infrastructure.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TiffanyLampId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TiffanyLampId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LuminousStudio.Infrastructure.Data.Entities.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TiffanyLampId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TiffanyLampId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("LuminousStudio.Infrastructure.Data.Entities.TiffanyLamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LampStyleId")
                        .HasColumnType("int");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("TiffanyLampName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("LampStyleId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("TiffanyLamps");
                });

            modelBuilder.Entity("LuminousStudio.Infrastructure.Data.Entities.Order", b =>
                {
                    b.HasOne("LuminousStudio.Infrastructure.Data.Entities.TiffanyLamp", "TiffanyLamp")
                        .WithMany("Orders")
                        .HasForeignKey("TiffanyLampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TiffanyLamp");
                });

            modelBuilder.Entity("LuminousStudio.Infrastructure.Data.Entities.ShoppingCart", b =>
                {
                    b.HasOne("LuminousStudio.Infrastructure.Data.Entities.TiffanyLamp", "TiffanyLamp")
                        .WithMany()
                        .HasForeignKey("TiffanyLampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TiffanyLamp");
                });

            modelBuilder.Entity("LuminousStudio.Infrastructure.Data.Entities.TiffanyLamp", b =>
                {
                    b.HasOne("LuminousStudio.Infrastructure.Data.Entities.LampStyle", "LampStyle")
                        .WithMany("tiffanyLamps")
                        .HasForeignKey("LampStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuminousStudio.Infrastructure.Data.Entities.Manufacturer", "Manufacturer")
                        .WithMany("tiffanyLamps")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LampStyle");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("LuminousStudio.Infrastructure.Data.Entities.LampStyle", b =>
                {
                    b.Navigation("tiffanyLamps");
                });

            modelBuilder.Entity("LuminousStudio.Infrastructure.Data.Entities.Manufacturer", b =>
                {
                    b.Navigation("tiffanyLamps");
                });

            modelBuilder.Entity("LuminousStudio.Infrastructure.Data.Entities.TiffanyLamp", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
